-- 한국 기업 기술블로그 추가
INSERT INTO blogs (name, company, rss_url, home_url) VALUES
    -- 국내 대기업 / 플랫폼
    ('네이버 클라우드 기술블로그',      '네이버클라우드',    'https://blog.ncloud-corp.com/feed',                'https://blog.ncloud-corp.com'),
    ('NHN Cloud MeetUp',            'NHN',            'https://meetup.nhncloud.com/rss',                  'https://meetup.nhncloud.com'),
    ('SK플래닛 기술블로그',            'SK플래닛',        'https://techtopic.skplanet.com/rss',               'https://techtopic.skplanet.com'),
    ('데브시스터즈 기술블로그',          '데브시스터즈',     'https://tech.devsisters.com/rss.xml',              'https://tech.devsisters.com'),
    ('야놀자 기술블로그',              '야놀자',          'https://medium.com/feed/yanolja',                  'https://medium.com/yanolja'),
    ('직방 기술블로그',                '직방',           'https://medium.com/feed/zigbang',                  'https://medium.com/zigbang'),
    ('리디 기술블로그',                '리디',           'https://ridicorp.com/feed/',                       'https://ridicorp.com/story'),
    ('왓챠 기술블로그',                '왓챠',           'https://medium.com/feed/watcha',                   'https://medium.com/watcha'),
    ('하이퍼커넥트 기술블로그',          '하이퍼커넥트',    'https://hyperconnect.github.io/feed.xml',          'https://hyperconnect.github.io'),
    ('쏘카 기술블로그',                '쏘카',           'https://tech.socarcorp.kr/feed.xml',               'https://tech.socarcorp.kr'),
    ('드라마앤컴퍼니 기술블로그',        '리멤버',         'https://blog.dramancompany.com/feed/',             'https://blog.dramancompany.com'),
    ('여기어때 기술블로그',             '여기어때',        'https://techblog.gccompany.co.kr/feed',            'https://techblog.gccompany.co.kr'),
    ('29CM 기술블로그',               '29CM',           'https://medium.com/feed/29cm',                    'https://medium.com/29cm'),
    ('무신사 기술블로그',              '무신사',          'https://medium.com/feed/musinsa-tech',             'https://medium.com/musinsa-tech'),
    ('올리브영 기술블로그',             '올리브영',        'https://oliveyoung.tech/rss.xml',                 'https://oliveyoung.tech'),
    ('인프런 기술블로그',              '인프런',          'https://tech.inflearn.com/rss.xml',                'https://tech.inflearn.com'),
    ('AB180 기술블로그',              'AB180',          'https://engineering.ab180.co/feed',                'https://engineering.ab180.co'),
    ('마켓컬리 데이터 기술블로그',       '컬리',           'https://medium.com/feed/kurly-tech-blog',          'https://medium.com/kurly-tech-blog'),
    ('지마켓 기술블로그',              '지마켓',          'https://dev.gmarket.com/feed',                    'https://dev.gmarket.com'),
    ('원티드 기술블로그',              '원티드',          'https://medium.com/feed/wantedjobs',              'https://medium.com/wantedjobs'),
    ('채널톡 기술블로그',              '채널코퍼레이션',    'https://channel.io/ko/blog/rss',                  'https://channel.io/ko/blog'),
    ('스포카 기술블로그',              '스포카',          'https://spoqa.github.io/rss',                     'https://spoqa.github.io'),
    ('플랫폼엘 기술블로그',            '롯데이커머스',     'https://platform-el.tistory.com/rss',              'https://platform-el.tistory.com'),
    ('카카오엔터프라이즈 기술블로그',    '카카오엔터프라이즈', 'https://tech.kakaoenterprise.com/feed',           'https://tech.kakaoenterprise.com'),
    ('LINE Financial 기술블로그',     'LINE Financial', 'https://engineering.linefinancial.com/ko/feed',    'https://engineering.linefinancial.com/ko'),
    ('SSG 기술블로그',                'SSG',            'https://medium.com/feed/ssg-tech',                'https://medium.com/ssg-tech'),

    -- 해외 빅테크
    ('Netflix Tech Blog',           'Netflix',        'https://netflixtechblog.com/feed',                'https://netflixtechblog.com'),
    ('Uber Engineering',            'Uber',           'https://www.uber.com/blog/engineering/rss/',       'https://www.uber.com/blog/engineering'),
    ('Airbnb Tech Blog',            'Airbnb',         'https://medium.com/feed/airbnb-engineering',       'https://medium.com/airbnb-engineering'),
    ('Spotify Engineering',          'Spotify',        'https://engineering.atspotify.com/feed/',          'https://engineering.atspotify.com'),
    ('Stripe Engineering',           'Stripe',         'https://stripe.com/blog/feed.rss',                'https://stripe.com/blog/engineering'),
    ('Dropbox Tech Blog',           'Dropbox',        'https://dropbox.tech/feed',                       'https://dropbox.tech'),
    ('GitHub Engineering',           'GitHub',         'https://github.blog/engineering/feed/',            'https://github.blog/engineering'),
    ('Meta Engineering',             'Meta',           'https://engineering.fb.com/feed/',                 'https://engineering.fb.com'),
    ('Google Developers Blog',       'Google',         'https://developers.googleblog.com/feeds/posts/default?alt=rss', 'https://developers.googleblog.com'),
    ('AWS Architecture Blog',        'AWS',            'https://aws.amazon.com/blogs/architecture/feed/',  'https://aws.amazon.com/blogs/architecture'),
    ('Cloudflare Blog',              'Cloudflare',     'https://blog.cloudflare.com/rss/',                'https://blog.cloudflare.com'),
    ('LinkedIn Engineering',         'LinkedIn',       'https://engineering.linkedin.com/blog.rss',        'https://engineering.linkedin.com'),
    ('Pinterest Engineering',        'Pinterest',      'https://medium.com/feed/pinterest-engineering',    'https://medium.com/pinterest-engineering'),
    ('Twitter Engineering',          'X (Twitter)',    'https://blog.twitter.com/engineering/en_us/blog.rss', 'https://blog.twitter.com/engineering'),
    ('Slack Engineering',            'Slack',          'https://slack.engineering/feed/',                  'https://slack.engineering'),
    ('Figma Engineering',            'Figma',          'https://www.figma.com/blog/feed/',                'https://www.figma.com/blog'),
    ('Discord Engineering',          'Discord',        'https://discord.com/blog/rss.xml',                'https://discord.com/blog'),
    ('Shopify Engineering',          'Shopify',        'https://shopify.engineering/feed.atom',            'https://shopify.engineering'),
    ('Notion Tech Blog',            'Notion',         'https://www.notion.com/blog/topic/tech/feed',     'https://www.notion.com/blog/topic/tech'),
    ('Canva Engineering',            'Canva',          'https://www.canva.dev/blog/engineering/feed.xml',  'https://www.canva.dev/blog/engineering'),
    ('Instacart Tech Blog',         'Instacart',      'https://tech.instacart.com/feed',                 'https://tech.instacart.com'),
    ('DoorDash Engineering',         'DoorDash',       'https://doordash.engineering/feed/',               'https://doordash.engineering'),
    ('Lyft Engineering',             'Lyft',           'https://eng.lyft.com/feed',                       'https://eng.lyft.com'),
    ('Etsy Engineering',             'Etsy',           'https://www.etsy.com/codeascraft/rss',            'https://www.etsy.com/codeascraft'),
    ('Grab Tech Blog',              'Grab',           'https://engineering.grab.com/feed.xml',            'https://engineering.grab.com'),
    ('Mercari Engineering',          'Mercari',        'https://engineering.mercari.com/en/blog/feed.xml', 'https://engineering.mercari.com/en/blog'),

    -- 해외 인프라 / DevOps / 클라우드
    ('HashiCorp Blog',              'HashiCorp',      'https://www.hashicorp.com/blog/feed.xml',         'https://www.hashicorp.com/blog'),
    ('Grafana Blog',                'Grafana Labs',   'https://grafana.com/blog/index.xml',              'https://grafana.com/blog'),
    ('DigitalOcean Blog',           'DigitalOcean',   'https://blog.digitalocean.com/rss',               'https://blog.digitalocean.com'),
    ('Datadog Engineering',          'Datadog',        'https://www.datadoghq.com/blog/engineering/feed', 'https://www.datadoghq.com/blog/engineering'),

    -- 해외 개발 커뮤니티 / 미디어
    ('Martin Fowler',               'ThoughtWorks',   'https://martinfowler.com/feed.atom',              'https://martinfowler.com'),
    ('The Pragmatic Engineer',       'Pragmatic Eng',  'https://newsletter.pragmaticengineer.com/feed',   'https://newsletter.pragmaticengineer.com'),
    ('InfoQ',                        'InfoQ',          'https://feed.infoq.com/infoq/infoq',             'https://www.infoq.com'),
    ('Dev.to',                       'Dev.to',         'https://dev.to/feed',                             'https://dev.to');
